import { LineEdit, AboutSlint, Button, VerticalBox } from "std-widgets.slint";
export component MerryWindow {
    in-out property <string> response;
    callback search(string);
    VerticalBox {
        Text {
            text: "Merry Dictionary";
            font-size: 24px;
            horizontal-alignment: center;
        }
        HorizontalLayout { 
            alignment: center;
            spacing: 5px;
            search-box := LineEdit {
                font-size: 14px;
                placeholder-text: "Enter a word...";
                accepted(text) => {
                    root.search(self.text);
                    self.text = "";
                }
            }
            btn := Button {
                text: "Search";
                clicked => {
                    root.search(search-box.text);
                    search-box.text = "";
                }
                enabled: search-box.text != "";
            }
        }
        Text {
            text: response;
            font-size: 15px;
            horizontal-alignment: left;
            wrap: word-wrap;
        }
        Rectangle {}
        AboutSlint {
            preferred-height: 50px;
        }
    }
}
